# TUPLES ARE IMMUTABLE
t1 = tuple()
t2 = ()
print(t1, t2)

t3 = (["1", "2"],)
print(type(t3))
# TUPLES VS LIST
# 1. TUPLES ARE FASTER AND MORE EFFICIENT
# 2. CONSTANT LISTS / NOT CHANGING SHOULD BE TUPLES
# 3. TUPLES ARE SAFER BECAUSE THEY DONT GET CHANGED
# 4. TUPLES CAN BE USED AS KEYS IN DICTIONARIES
# 5. MEMORY EFFICIENT
